### ISSUE TITLE
chore: update tooling

### ISSUE THREAD

**Issue by OneLiL05** [mindenit/ui#37]
## Tasks

- [x] move to monorepo;
- [x] update to Vite 6;
- [x] add CI scripts;
- [x] move from `cva` to Tailwind Variants.
